config/routes.rb
Rails.application.routes.draw do
  resources :organizations
  resources :sales
  resources :stocks
  resources :products
  resources :providers
  resources :categories
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'
end

app/models/stock.rb
class Stock < ApplicationRecord
    belongs_to :product
    
    validates :lot, uniqueness: true

    def stock_name
        return self.product.name
    end

    def stock_price
        return self.product.sale_price
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]

  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
    @products = Product.all
  end

  # GET /stocks/1/edit
  def edit
    @products = Product.all
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)
    @stock.lot = SecureRandom.hex(4)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:quantity, :min_quantity, :product_id)
    end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_form.html.erb
<%= simple_form_for(stock) do |f| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.association :product %>
  <%= f.input :quantity %>
  <%= f.input :min_quantity %>

  <div class="actions">
    <%= f.submit class:"btn btn-success" %>
  </div>
<% end %>

app/views/stocks/_product_card.html.erb
<a class="list-group-item" href="<%= product_path(product_id) %>">
    <div class="row">
        <div class="col-xs-6 col-md-3">
            <img src="<%= picture %>" class="img-rounded pull-left list-img" />
            <h4 class="list-group-item-heading">
                <%= name %>
            </h4>
            <p class="list-group-item-text">
                <%= description %>
            </p>
        </div>
        <div class="col-xs-6 col-md-3">
            <p class="list-group-item-text"><b>In Stock</b></p>
            <p class="list-group-item-text">$
                <%= quantity %>
            </p>
        </div>
        <div class="col-xs-6 col-md-3">
            <p class="list-group-item-text"><b>Sale Price</b></p>
            <p class="list-group-item-text">$
                <%= sale_price %>
            </p>
        </div>
        <div class="col-xs-6 col-md-3">
            <p class="list-group-item-text"><b>Lot Code</b></p>
            <p class="list-group-item-text">#
                <em><%= lot %></em>
            </p>
        </div>
    </div>
</a>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<p id="notice">
  <%= notice %>
</p>

<div class="bootcards-list">
  <div class="panel panel-default">
    <div class="list-group">
      <% @stocks.each do |stock| %>
        <%= render partial:'stocks/product_card', locals: {
          picture: stock.product.picture.url,
          name: stock.product.name,
          description: stock.product.description,
          quantity: stock.quantity,
          sale_price: stock.product.sale_price,
          purchase_price: stock.product.purchase_price,
          lot: stock.lot,
          product_id: stock.product_id,
          } %>
          <% end %>
    </div>
  </div>
</div>



<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Back', stocks_path %>